source 'https://rubygems.org'
# apps/mobile/Gemfile
# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby "3.4.2"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 7.0.0', '< 8.0'
gem 'xcodeproj', '< 1.26.0'
gem 'concurrent-ruby', '< 1.3.4'
# Required for Ruby 3.4.2 compatibility
gem 'bigdecimal', '~> 3.1'
